### ISSUE TITLE
Ova !> fails after sort!

### ISSUE THREAD

**Issue by neverfox** [zcaudate/hara#14]
`scoreboard` and `sim-game` taken from the docs
```
(sim-game scoreboard "Bill")
;; normal output

(dosync (sort! scoreboard [:attempts] >))

(sim-game scoreboard "Bill")
;; java.lang.ClassCastException: clojure.lang.ArraySeq cannot be cast to clojure.lang.IFn
```

**Comment by zcaudate** [comment]
thanks for that. let me check what's happening..

**Comment by zcaudate** [comment]
okay, it's a small problem with sort! not turning the underlying data structure into a vector. made the fix and will push out a new version asap

**Comment by zcaudate** [comment]
okay, the 2.3.6 version has the fix.
