### ISSUE TITLE
Minimal failing diff cases

### ISSUE THREAD

**Issue by danielcompton** [zcaudate/hara#15]
I was doing some test.checking of hara.data.diff and found this minimal failing case

```cli
(->> (hara.data.diff/diff [] [[:a]])
     (hara.data.diff/patch [[:a]]))
```

which throws

```
ClassCastException clojure.lang.PersistentVector cannot be cast to clojure.lang.IPersistentMap  clojure.lang.RT.dissoc (RT.java:834)
```

Do you have any ideas why this might be happening?

**Comment by zcaudate** [comment]
oh thanks! but there may be a problem with the specification of the tests. diff works with maps, not vectors.

**Comment by danielcompton** [comment]
Ah, my mistake. It worked pretty well on vectors, so I added them to the spec.

**Comment by zcaudate** [comment]
hahaha. how so? love to see a working example

**Comment by zcaudate** [comment]
I'm gunna close this for now. Feel free to open it up again if you see fit. I would love to see your work with the test.check spec if that is possible.

**Comment by danielcompton** [comment]
```cli
(defspec diffs-successfully-apply 100
  (prop/for-all [before (gen/map gen/keyword gen/any)
                 after (gen/map gen/keyword gen/any)]
    (= after (->> (d/diff before after)
                  (d/patch before)))))
```

Here's my passing spec. 

I also found it worked for diff/patching

```cli
[{:a {:b {:c :d}}}]
; to
[{:a {:b {:d :d}}}]
    
; and 

[{:a [{:x 1} {:y 1} {:z 1}]}]
; to
[{:a [{:x 2} {:z 1} {:y 1}]}]
```
