### ISSUE TITLE
support for timezones and holiday calendars in the scheduler

### ISSUE THREAD

**Issue by henryw374** [zcaudate/hara#17]
hi. we are still using the old cronj scheduler lib and needed to support timezones and holiday calendars. iow - a task has a schedule as normal, but it is triggered based on a match with the time in its timezone, not the timezone of the vm. also a task can have a holiday calendar, so it would not run on e.g. new years day etc.

i was able to add this feature by alter-var-root'ing `cronj.data.scheduler/signal-tick` to have the behaviour.

curious if you'd consider this feature for hara scheduler?

**Comment by zcaudate** [comment]
I think you can also do that with the scheduler. I've never considered the use case but if you are using alt-var-root, I can potentially insert a wrapper function to modify the scheduler. 

I'm a little confused with the VM timezone versus date timezone. Can you give a more concrete example?

**Comment by ohlo** [comment]
ok so say your server is running in london timezone, but you want to specify a job runs at 4 am in NY. you could specify this as 9am london, except for when DST is out of sync. also in our case we have end users who specify cron schedule on a gui, so they would rather say 4am NY, than 9am LN ... ie having to do the mental calculation.

so in the signal-tick fn, for each task, the tick time (e.g. 9am UTC) is converted to the timezone of the task (4am NY) and then the match is tried. the holiday bit then takes that further, checking if the converted time falls within a holiday period.

**Comment by zcaudate** [comment]
I get what you mean now. Essentially you need a way to specify timezone. 

have a look at:
https://github.com/zcaudate/hara/blob/master/src/hara/io/scheduler.clj#L17-L24

you can specify your default timezone here:
https://github.com/zcaudate/hara/blob/master/src/hara/io/scheduler.clj#L41

let me have a think about the wrapper for an additional check. the code for triggering is here:
https://github.com/zcaudate/hara/blob/master/src/hara/io/scheduler/array.clj#L48-L51

feel free to have a play but do let me know if this is going in the right direction. if you can, can you give an example of how holidays are checked

**Comment by ohlo** [comment]
Thanks for the info. 
the timezones are per-task. I think the tz config you showed me is for the scheduler?

its definitely a hack but i am using the desc field of the task to hold the timezone and the name of a holiday calendar.

the holiday is just a call to a fn like `(holiday? time "usa holidays")` and that fn does a lookup in a table

**Comment by zcaudate** [comment]
yeah it is for the scheduler. Not sure if it’s possible to do it for a task but will have a think

**Comment by zcaudate** [comment]
I'm going to close this because it's not that easy. This really is a library for daily routines. Adding support for special circumstances like holidays (for example Chinese and Indian holidays fall on different days every year) will complicate things too much.
