### ISSUE TITLE
crazy number of reflection warnings

### ISSUE THREAD

**Issue by ztellman** [zcaudate/hara#2]
I'm only seeing this because I'm trying Ultra out, but an alarming number of these warnings are in namespaces like `primitive` or `util` that seem to be trying to do performance-y things.  I strongly suggest turning on `*warn-on-reflection*` in your `:global-vars` and cleaning these up.

**Comment by zcaudate** [comment]
I haven't used ultra before... But the entire hara.reflect library is about doing reflection... So I'm not really sure how I can clean it up :) can you give me some pointers?

**Comment by ztellman** [comment]
I've opened up #3, which will help you address this.  Sorry to submit such an unconstructive issue initially.

**Comment by zcaudate** [comment]
okay I see all the warnings pop up. is it just a matter of adding some type hints to the code: i.e.: ^java.lang.Class?

    (defn interface?
      [^java.lang.Class class]
      (.isInterface class))

**Comment by ztellman** [comment]
Yes.

**Comment by zcaudate** [comment]
I've got a problem with some examples that have more than one type of input but have the same method signature:

    1. The `.getName` method is common across `clojure.lang.Symbol` as well as `java.lang.Class`. 
https://github.com/zcaudate/hara/blob/aff2510b696dc911c647f9c842b90515269ec0b4/src/hara/reflect/pretty/classes.clj#L14 and so the method can take either a Class or a Symbol

   2. I am reflecting against Classes, Methods. Fields and Constructors here:
 https://github.com/zcaudate/hara/blob/aff2510b696dc911c647f9c842b90515269ec0b4/src/hara/reflect/element/common.clj#L22-L32 and they all implement .getModifiers without a proper interface.

In this case, reflection is still necessary... unless there is another way around it

**Comment by zcaudate** [comment]
I've pushed changes to the code base fixing all the warnings except for a few methods mentioned above

`lein check` will show the functions that I'm having trouble wit:

**Comment by zcaudate** [comment]
All warnings fixed up =)
