### ISSUE TITLE
Convert project to cljc

### ISSUE THREAD

**Issue by danielcompton** [zcaudate/hara#20]
A lot of hara would be really useful from ClojureScript. Most of the hara codebase is written in platform independent Clojure, so porting the code wouldn't be too tricky. The harder part is the surrounding infrastructure of
- [ ] hydrox https://github.com/helpshift/hydrox/issues/9
- [ ] repack https://github.com/zcaudate/lein-repack/issues/17
- [ ] running tests in clj and cljs

None of this is insurmountable, but there is a bit of work to do to get there.

Relates to #18.

**Comment by zcaudate** [comment]
there are parts of hara that cannot be ported:

- class, object, reflect, io, concurrent

namespaces that should have no problems being ported:

 - component, data, event, extend, sort, function, group, string

namespaces that may need work:

- common, time

I would recommend having a seperate project and porting one namesake at a time. The easiest should be data, sort, group and string.

**Comment by zcaudate** [comment]
dalap offers a much cleaner/better solution than cljx/cljc - even though cljc is definitely easier to work with on smaller projects.

http://birdseyesoftware.github.io/lein-dalap.docs/

let me know what you think

**Comment by zcaudate** [comment]
looking at dalap again, it may be better to have a custom approach to patch cljs functions. let me have a think about this.

**Comment by danielcompton** [comment]
> I would recommend having a seperate project and porting one namesake at a time. The easiest should be data, sort, group and string.

What do you mean by separate project? Are you suggesting a new Git repo, maven dependency, e.t.c.? What would the long term plan be for merging them? Not everything would need to be ported to cljc, class, object, e.t.c. could happily stay as clj files.

> dalap offers a much cleaner/better solution than cljx/cljc

I'm not so convinced. cljc is supported natively by the last two versions of Clojure and doesn't require any extra tooling. Cursive also supports it natively which means that all of Cursive's static analysis works on it. Personally I've used reader conditionals for quite a while and have never really had a problem with them.

Dalap hasn't had any commits for two years, I'm not sure how well maintained it is.

Speaking as an outside contributor, the fewer unusual dependencies, build tools, and processes that I need to learn to contribute, the better. If there's a compelling reason for a tool, then use it, but I'm not too sure what the downsides of cljc are.

It's your project though :)

**Comment by danielcompton** [comment]
Just read your comment on #18, will reply here to keep them together:

> To tell you the truth, I think cljc is by far, the worst thing that has happened to clojure because it harks back to the bad old days of c/c++ preprocessor macros. They made code horrendously difficult to read because platform specific code started to fragment the codebase.

I haven't seen a lot of dalap code, but I don't see too much difference between cljc and [this](https://github.com/BirdseyeSoftware/lein-dalap/blob/master/examples/hello_world/src/clj/hello_world/core.clj)

> The interesting thing about clojure is that most people don’t mind because most libraries tend to be less than 1000 loc and so using cljx doesn’t really matter. However, hara is different: It’s big, it’s modular and it relies on automation for project maintenance. I find it hard enough reading/reasoning about code, let alone having some preprocessor code for platform specific behaviour be sprinkled throughout the codebase.

Sure, cljc might make code slightly harder to read, but it seems like you're going to need to write pretty much the same platform specific code in whichever preprocessor you choose, be that cljx, cljc, or dalap. If you find that a namespace has way too many reader conditionals then you can always just split it into a clj and cljs file.

In my experience with cljx code, the source to sink distance was a lot larger as you had a cljx file getting processed and sent to another location, and you had another build tool running to do that processing. At least with cljc, everything stays in one file.

> In my option, the test of good code is readability - and I’m not convinced at all of the advantages that cljc offers to a large code base in the long run. Once fragmentation gets into a codebase, it’s hard to stop the rot and I prefer to stay on the side of vigilance.

Totally understand where you're coming from. From the sounds of things I like cljc a lot more than you do, but that's fine :).

**Comment by zcaudate** [comment]
yep, having a seperate cljs project for the time being. the core of hara (common, data, sort) has been stable for a while and there's no plan for a major rewrite so there wouldn't be too much work to 

re cljc... just because something is canonical doesn't mean that it's a good idea to use.
- refer to javascript, the good parts
- totally schema-less databases
- platform dependent code

You have to understand that I wrote the build tools and processes in order to write the library - not the other way around. So for me, the process is probably more important than the source code. It's taken about 5 times the time to write those tools as well as the documentation over the actual the source code. Yes, you are right they are not conventional, the project has reached a point where I can deploy my website as well as 40 clojure projects with just a couple of commands. 

I'm sticking to that process and I hope that you can too =)

**Comment by zcaudate** [comment]
I’ll be more than happy to go through the project and how I manage it if you are interested.

**Comment by zcaudate** [comment]
Closing this issue for now. I personally don't have an interest in making this cljc compliant.
