### ISSUE TITLE
humble request about language

### ISSUE THREAD

**Issue by jmarca** [zcaudate/hara#23]
In the concurrent documentation, would you be kind enough to avoid using master/slave terminology.  For example: https://github.com/zcaudate/hara/blob/64bfd18040f3c5aa972b576c59690aa1b27d925d/hara-concurrent.html#L112  Primary/secondary, leader/follower and other terms are less loaded.

It was recently pointed out to me that some people find that offensive/triggering, AND that slavery still exists.  I don't mean to start a flame war though.  

PS. great code and great documentation.  I'm new to clojure and great documentation sites like yours help tremendously.

**Comment by zcaudate** [comment]
you're right. I'll make the necessary adjustment. primary/replica maybe?

**Comment by zcaudate** [comment]
this has been fixed to primary/follower in the newest code
