### ISSUE TITLE
[Component] Cannot pass state from "-start" to "-stop"

### ISSUE THREAD

**Issue by aleadag** [zcaudate/hara#30]
First, thanks for the great work.

I am reading the document of "Component", and tried the code. In the "Trap" component, it looks like the "-start" function will pass ":thread" information to "-stop" function. But when I run the code, it turns out the :thread is nil. Here goes the "Trap" component code:
```
(defrecord Trap []
  Object
  (toString [obj]
    (let [selected [:location :output]]
      (str "#trap" (-> (into {} obj)
                       (select-keys selected)
                       (update-in [:output] deref)))))

  component/IComponent
  (-start [trap]
    (assoc trap
           :thread (future
                     (println (str "Starting trap in "
                                   (:location trap) "\n"))
                     (last (iterate trap-bug trap)))))

  (-stop [{:keys [thread output] :as trap}]
    (do
      (println (str "Stopping trap in " (:location trap)))
      (future-cancel thread) ;; thread is nil
      (reset! output nil)
      (dissoc trap :thread))))
```

**Comment by zcaudate** [comment]
Hey there,

I tried the code and it works fine for me:

 (:thread (component/start (map->Trap {:location "outdoors"
                                        :output (atom {})})))
=>  #object[clojure.core$future_call$reify__6962 0x84d94a3 {:status :ready, :val nil}]
 
how are you using it?

**Comment by aleadag** [comment]
Thanks for the quick response. I pasted my code here: https://gist.github.com/aleadag/d83ff3aadaec1666cc647d1275047f13

**Comment by zcaudate** [comment]
please see the comment on the gist. I think this should be resolved. let me know if there are any issues.
