### ISSUE TITLE
hara.io.archive.zip breaks on Java 9

### ISSUE THREAD

**Issue by saeidscorp** [zcaudate/hara#35]
After upgrading to java 9, hara causes this exception:

```java.lang.ClassNotFoundException: com.sun.nio.zipfs.ZipFileSystem, compiling:(hara/io/archive/zip.clj:1:1)```

I tried to see if it's trivial to fix and request a PR, but I don't know where to start; as `com.sun.nio.zipfs.ZipFileSystem` seems to be undocumented.

Any ideas?
Thanks.

**Comment by zcaudate** [comment]
Yeah. Java 9 also breaks `hara.reflect`. I'm not happy. I'm also a little bit time poor at the moment so am sticking to Java 8

Is Java 9 a necessity for you? If it is, then it'll be great if you can put in a pull request. If you have time to do some digging around, have a look at the class that is being returned here:
https://github.com/zcaudate/hara/blob/master/src/hara/io/archive.clj#L35-L38

`hara.io.archive.zip` is not needed in this case and then you can look at implementing the [necessary functions](https://github.com/zcaudate/hara/blob/master/src/hara/io/archive/zip.clj#L10-L52) that go along with that class.

**Comment by zcaudate** [comment]
@saeidscorp: actually, it wasn't too hard a [fix](https://github.com/zcaudate/hara/blob/d7da3ec534974fadd637fecd6b225621f4402cb1/src/hara/io/archive/zip.clj).

Java 9 had renamed the class to be jdk.nio.zipfs.ZipFileSystem instead of com.sun.nio.zipfs.ZipFileSystem. The functionality remained the same.

I'll push out a new version in the next couple of days.

**Comment by saeidscorp** [comment]
I overcome the issue with `hara.io.archive.zip` by adding `[com.github.marschall/zipfilesystem-standalone "1.0.1"]` dependency. [its github page](https://github.com/marschall/zipfilesystem-standalone)
Now at least the exception is not thrown. But not sure whether it works correctly. Later I try to revamp it to work with Java 9 flawlessly.

Right now I ran into issues with `hara.reflect` and `hara.io.classloader`.

**Comment by saeidscorp** [comment]
Ha! Thanks!

So I'll dig further into `hara.reflect` and `hara.io.classpath` which is throwing method-not-found kinda exception for `getURLS` in https://github.com/zcaudate/hara/blob/20631b1c0890556f8d70941f4713c172226021f9/src/hara/io/classloader.clj#L13

Maybe this can be a place to start: http://java9.wtf/class-loading/

Thanks again for your time.

**Comment by zcaudate** [comment]
They are all fixed in the newest commit: https://travis-ci.org/zcaudate/hara/builds/339776610

    - With classloader, on Java 9, the default classloader is not java.net.URLClassloader anymore.
    - With reflection, Java 9 has a flag that needs to be set in order for certain reflection operations to work `--illegal-access=permit`

Will publish and ping you.

**Comment by zcaudate** [comment]
[v2.8.2](https://clojars.org/zcaudate/hara.io.archive) is pushed to clojars.

Let me know if you find anything else.

**Comment by saeidscorp** [comment]
Awesome!

Although when used in an empty project and without `profiles.clj` present, it works with no issues at all. And when I use the custom `profiles.clj` with lucidity included, the same exception occurs.

`im.chit/lucidity` has a dependency on `im.chit` versions of `hara` which I think causes the same exception on REPL startup.

Maybe bump the `hara` versions on `lucid` (and move to `zcaudate` group :)) ?

Thanks for your time and effort. And a really great library ;))

**Comment by saeidscorp** [comment]
Sorry, didn't notice the `zcaudate/lucid`. as the documentation for lucid was inconsistent with version and group id. http://docs.caudate.me/lucidity/lucid-core.html says `im.chit/lucid.core "1.4.0"`

**Comment by zcaudate** [comment]
@saeidscorp: thanks. it's fixed.
