### ISSUE TITLE
Code for parsing cron tab format

### ISSUE THREAD

**Issue by devth** [zcaudate/hara#36]
Could you please point me to the code that parses / uses the cron string? I found `parse-tab` but that just splits the components out into an array. How does that get get translated into schedulable intervals? Thanks.

**Comment by zcaudate** [comment]
the design is that the ticker has a watch function that will trigger the handler associated with each task on if it is matched.

https://github.com/zcaudate/hara/blob/master/src/hara/io/scheduler/array.clj#L54-L59

it calls match-array

https://github.com/zcaudate/hara/blob/master/src/hara/io/scheduler/tab.clj#L127-L141

**Comment by devth** [comment]
Got it. Thank you!

Using `scheduler` to add cron-like ability to my chat bot: https://github.com/yetibot/yetibot/issues/150 :)

**Comment by zcaudate** [comment]
very cool. I'll have to have a play with it at some point.
