### ISSUE TITLE
namespace 'hara.string.case' not found when requiring hara.image (deps.edn)

### ISSUE THREAD

**Issue by cbowdon** [zcaudate/hara#40]
Inspired by dj-kitty.gif I tried to play around with hara.image but unfortunately got this namespace exception.

Steps to reproduce:
```clojure
$ clojure  # in same directory as deps.edn, below
$ user=> (require '[hara.image])
CompilerException java.lang.ClassNotFoundException: hara.string.case, compiling:(hara/image/awt/common.clj:13:19)
```

deps.edn:
```clojure
{:deps {org.clojure/clojure {:mvn/version "1.9.0"}
        zcaudate/hara {:mvn/version "2.8.7"}}}
```

If I `(require '[hara.image])` again in the same REPL, I get this error instead:

    CompilerException java.lang.Exception: namespace 'hara.image.awt.common' not found, compiling:(hara/image/base.clj:1:1)                                                                                      

Am I doing something wrong?

**Comment by zcaudate** [comment]
Hmm... 

Can you try and use zcaudate/hara.image instead?

**Comment by zcaudate** [comment]
I'm not sure what's with deps.edn because I've never used it.

it doesn't work for me even if I put in the dependency explicitly:

```
{:deps {org.clojure/clojure {:mvn/version "1.9.0"}
        zcaudate/hara.image {:mvn/version "2.8.7"}
        zcaudate/hara.string.case {:mvn/version "2.8.7"}}}
```

are you familiar with leiningen/boot?

**Comment by zcaudate** [comment]
for whatever reason, you have to include `hara.string.case` first:

```
Clojure 1.9.0
user=> (require 'hara.string.case)
nil
user=> (require 'hara.image)
nil
user=>
```
also, the animate function is not in `2.8.7` i wrote the post as a bit of a joke,

to get it working in the current `2.8.7` version, you need to define it explicitly: 

(see https://github.com/zcaudate/hara/blob/master/src/hara/image/base/display.clj#L132-L142)

```

```

**Comment by cbowdon** [comment]
Ah, thanks for explaining this (and for the animate function).

I’ll rename this issue to include deps.edn so that it’s easy for other people to find.
