### ISSUE TITLE
Small documentation error for hara.event

### ISSUE THREAD

**Issue by MatthewDarling** [zcaudate/hara#8]
On the [docs page for hara.event](http://docs.caudate.me/hara/hara-event.html), section 2.3 has the same text as section 2.2, so ```deflistener``` isn't actually explained.

I think that's based on [this line](https://github.com/zcaudate/hara/blob/7d44af5ab4c47ad1374cb2901cc9ded710132564/test/documentation/hara_event.clj#L93), based on a quick search.

**Comment by zcaudate** [comment]
Thanks Matt,

I'll get that updated asap :)

**Comment by MatthewDarling** [comment]
Looks like this is resolved now! Thanks :)

**Comment by zcaudate** [comment]
thanks!
