### ISSUE TITLE
Dynamic binding of listeners (like managers)

### ISSUE THREAD

**Issue by alexander-yakushev** [zcaudate/hara#9]
I like the idea of having global listeners for things that are global by nature (like, always drop errors into logstash no matter what dynamic scope is established). But sometimes I want to dynamically control how to handle signals, just like I do with raises. What would be the correct way to do it?

**Comment by zcaudate** [comment]
Can you give an example of what you are doing? I can sort of see it but would need the context to give a proper suggested

**Comment by alexander-yakushev** [comment]
I have a function deep down inside the library (my library) that has silent and verbose modes. In one application I need to use that function in two different modes, so I'd like to just send a signal with verbose data from the function, and then somewhere on top either discard it or do something with it (print to stdout, drop into logstash, maybe schedule for reprocessing later).

What I basically want is the `signal`/`handler-bind` functionality, the ability to dynamically bind handlers for signals.

**Comment by zcaudate** [comment]
are you able to pass the :silent and :verbose mode flags as data?

**Comment by alexander-yakushev** [comment]
The decision whether to be silent or verbose should come from the worker function, but decided above in the management section.

**Comment by zcaudate** [comment]
there is an escalate macro which allows adding new data to the issue bring raised. That may be able to suffice.

I'm not sure how to do it the other way because it is a global set of handlers that can be tuned to act on specific combinations of data. 

The individually bound handlers that you're asking for is not what this was designed for.

**Comment by alexander-yakushev** [comment]
Escalate and issues don't fit here because they enforce non-local exit if not caught by a handler. Signals on the other hand do nothing by default unless you handle them somehow.

And the global signal handlers don't cover all usecases because they are non-local, so they often lack the necessary context of how the signal should be reported.

Something like:
```clojure
(defn plus [a b]
  (signal :plus-debug {:a a, :b b, :action "Adding"})
  (+ a b))

(plus 3 4)
;=> 7

(manage-signals (plus 5 6)
  (on :plus-debug s (prinltn (:action s) (:a s) "and" (:b s))))
;; Adding 5 and 6
;=> 11
```
I don't see why you say it wasn't designed for it when issues already have dynamically scoped handlers instead of global ones. The lack of this functionality seems like a setback to me compared to Common Lisp.

**Comment by zcaudate** [comment]
Oh! now I understand what you need. Apologies. I still had my head around 'issues'.

you can actually add a default behaviour to an issue to not raise an exception if not handled... but let me have a think about this :)

**Comment by zcaudate** [comment]
would this be of any use?
http://docs.caudate.me/hara/hara-event.html#default

**Comment by alexander-yakushev** [comment]
```clojure
(defn dynamic-signal [signal-type content]
  (manage (raise [signal-type content]
                 (option ::noop [] nil)
                 (default ::noop))))

(defn plus [a b]
  (dynamic-signal :plus-debug {:action "Adding" :a a :b b})
  (+ a b))

(plus 2 3)
;=> 5

(manage (plus 5 6)
        (on :plus-debug [action a b]
            (println action a "and" b)
            (continue)))
;; Adding 5 and 6
;=> 11
```
Works as expected, thanks! I might write the wrapper macro for `manage` that supports something like `(on-signal ...)` so that I don't have to say `(continue)` explicitly, but overall this solves my immediate problem.

**Comment by zcaudate** [comment]
Cool... Thinking about this again, the use case here would probably be better with `raise`. `signal` creates a lightweight construct that doesn't have as much options as an `issue`.

Can this be closed?

**Comment by alexander-yakushev** [comment]
Yes, my question is answered, thank you!
